-- Schema definition for the departments and employees

-- drop table
DROP TABLE presidents;

-- create new table
CREATE TABLE presidents 
   ("PRESIDENTID" integer, 
	"FIRSTNAME" VARCHAR(45), 
	"LASTNAME" VARCHAR(45), 
	"STARTYEAR" integer, 
	"ENDYEAR" integer, 
	"IMAGEPATH" VARCHAR(80), 
	"BIO" VARCHAR(700)
   );
   
SELECT PRESIDENTID, FIRSTNAME, LASTNAME, STARTYEAR, ENDYEAR, IMAGEPATH, BIO
FROM PRESIDENTS 
ORDER BY PRESIDENTID;

SELECT PRESIDENTID, FIRSTNAME, LASTNAME, STARTYEAR, ENDYEAR, IMAGEPATH, BIO
FROM PRESIDENTS
WHERE PRESIDENTID = 1
ORDER BY PRESIDENTID;